### ISSUE TITLE
Pod::Weaver missing?

### ISSUE THREAD

**Issue by gregoa** [rafl/nanomsg-raw#6]
perldoc is quite unhappy with the pod in lib/NanoMsg/Raw.pm and lib/NanoMsg/Raw/Message.pm, and the pod2man output also is not ideal. From looking the files, my impression is that they use Pod::Weaver notation, but then they should probably be processed at some point in the release process, I guess.

Cheers,
gregor, Debian Perl Group

**Comment by borisz** [comment]
Thanks Gregor, I'll fix it soon/now

**Comment by gregoa** [comment]
On Thu, 03 Nov 2016 14:25:18 -0700, Boris Zentner wrote:

> Thanks Gregor, I'll fix it soon/now

Great, thank you!

**Comment by gregoa** [comment]
Still present in 0.09, despite the entry in Changes :)

**Comment by borisz** [comment]
Thanks Gregor,
I've merged your patch and hope pod2man is now happier.
( should be on CPAN in a few hours )
